version: '2'
services:
    campaignmanagercore-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb campaignmanagercore-mongodb-config
    campaignmanagercore-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    campaignmanagercore-mongodb-config:
        image: mongo:3.6.3
        container_name: campaignmanagercore-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
